# Generated by Django 5.0 on 2025-04-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adminconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='photo',
            field=models.ImageField(null=True, upload_to='visitor_photos/'),
        ),
    ]
